// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get_profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get Shubham Sharma's professional profile summary (Android developer).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: "Shubham Sharma",
      title: "Sr. Software Engineer (Android) at Experian",
      location: "Bangalore, IN",
      experience_years: 7,
      summary: "Android Developer with 7+ years of experience designing and developing high-performance, scalable mobile applications with millions of downloads. Expertise in Kotlin, Jetpack, MVVM, and CI/CD. Reduced app size by 30%, achieved 90% test coverage.",
      current_company: "Experian",
      current_role: "Sr. Software Engineer (Android)",
      companies: ["Experian", "Caspex (Walmart)", "Xebia (Walmart)", "BlueStone", "NoBroker", "Zonolith"],
      education: "B.Tech. in Computer Science, Rajasthan Technical University (2013-2017)",
      website: "https://www.bittslife.xyz/"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/get_contact.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_contact_default = defineTool2({
  name: "get_contact",
  title: "Get contact info",
  description: "Get public contact information for Shubham Sharma.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const contact = {
      email: "shubhamoksharma@gmail.com",
      phone: "+91-9672460166",
      location: "Bangalore, IN",
      whatsapp: "https://wa.me/919672460166",
      website: "https://www.bittslife.xyz/"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
      structuredContent: contact
    };
  }
});

// src/lib/mcp/tools/get_skills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_skills_default = defineTool3({
  name: "get_skills",
  title: "Get skills",
  description: "List Shubham Sharma's Android/mobile development skills and technologies.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const skills = {
      languages: ["Kotlin", "Java", "SQL"],
      android: ["Jetpack Compose", "Jetpack", "MVVM", "MVI", "Coroutines", "Flow", "Room", "Hilt", "Dagger", "Retrofit"],
      tools: ["Android Studio", "Git", "Firebase", "Gradle", "ProGuard/R8"],
      testing: ["JUnit", "Espresso", "Mockito", "UI Automator"],
      devops: ["CI/CD", "GitHub Actions", "Fastlane", "Jenkins"],
      architecture: ["Clean Architecture", "MVVM", "MVI", "Modularization"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(skills, null, 2) }],
      structuredContent: skills
    };
  }
});

// src/lib/mcp/tools/list_projects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "List projects",
  description: "List featured projects and apps by Shubham Sharma.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const projects = [
      {
        name: "Brain Teaser AI Game",
        status: "Coming Soon (Closed Beta)",
        launch_date: "2026-05-01",
        description: "AI-powered Android brain training puzzle game with 10+ mini games and endless AI-generated puzzles.",
        url: "https://www.bittslife.xyz/#/brain-teaser"
      },
      {
        name: "Experian Android App",
        role: "Sr. Software Engineer (Android)",
        description: "Built Personal Info SDUI components, Hosted App Flow for banks (Ollo, Merrick), and the Wallet Genius feature that recommends optimized cards by user goal."
      },
      {
        name: "Walmart Protection Plan Hub",
        role: "Sr. Software Engineer (Caspex)",
        description: "Built the Protection Plan Hub and Amends flow, driving a 15% increase in protection plan adoption and letting customers edit purchases post-checkout."
      },
      {
        name: "Walmart OmniScheduler",
        role: "Consultant (Xebia)",
        description: "Designed the OmniScheduler Module for Oil & Tire Change services, reducing scheduling time by 30% and increasing appointment bookings by 25%. Maintained 90%+ test coverage."
      },
      {
        name: "BlueStone App",
        role: "Senior Software Engineer",
        description: "Jewelry e-commerce Android app. Reduced app size by 30% via ProGuard/R8; +20% user retention from new features."
      },
      {
        name: "NoBroker App",
        role: "Android Developer",
        description: "Real-estate Android app; feature development and performance optimizations."
      }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(projects, null, 2) }],
      structuredContent: { projects }
    };
  }
});

// src/lib/mcp/tools/get_brain_teaser_info.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_brain_teaser_info_default = defineTool5({
  name: "get_brain_teaser_info",
  title: "Get Brain Teaser AI Game info",
  description: "Get launch, feature, and early-access info for the Brain Teaser AI Game Android app.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Brain Teaser AI Game",
      platform: "Android",
      status: "Coming Soon \u2014 Closed Beta",
      launch_date: "2026-05-01",
      landing_page: "https://www.bittslife.xyz/#/brain-teaser",
      early_access_whatsapp: "https://wa.me/919672460166?text=Hi!%20I%20want%20early%20access%20to%20Brain%20Teaser%20AI%20Game",
      highlights: [
        "10+ mini games",
        "Endless AI-generated puzzles",
        "Personalized adaptive difficulty",
        "Daily challenges"
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "shubham-portfolio-mcp",
  title: "Shubham Sharma Portfolio MCP",
  version: "0.1.0",
  instructions: "Public MCP server for Shubham Sharma's Android developer portfolio and the Brain Teaser AI Game landing page. Use these tools to answer questions about Shubham's profile, skills, contact info, and projects (including the Brain Teaser AI Game launching May 1).",
  tools: [get_profile_default, get_contact_default, get_skills_default, list_projects_default, get_brain_teaser_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
